# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [9]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

### Step 4. Create columns for the dataset

In [14]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class
iris['sepal_length'] = [None] * 149
iris['sepal_width'] = [None] * 149
iris['petal_length'] = [None] * 149
iris['petal_width'] = [None] * 149
iris['class'] = [None] * 149

,5.1,3.5,1.4,0.2,Iris-setosa,sepal_length,sepal_width,petal_length,petal_width,class
0,4.9,3.0,1.4,0.2,Iris-setosa,None,None,None,None,None
1,4.7,3.2,1.3,0.2,Iris-setosa,None,None,None,None,None
2,4.6,3.1,1.5,0.2,Iris-setosa,None,None,None,None,None
3,5.0,3.6,1.4,0.2,Iris-setosa,None,None,None,None,None
4,5.4,3.9,1.7,0.4,Iris-setosa,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Iris-virginica,None,None,None,None,None
145,6.3,2.5,5.0,1.9,Iris-virginica,None,None,None,None,None
146,6.5,3.0,5.2,2.0,Iris-virginica,None,None,None,None,None
147,6.2,3.4,5.4,2.3,Iris-virginica,None,None,None,None,None
148,5.9,3.0,5.1,1.8,Iris-virginica,None,None,None,None,None

### Step 5.  Is there any missing value in the dataframe?

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

### Step 7. Good, now lets substitute the NaN values to 1.0

### Step 8. Now let's delete the column class

### Step 9.  Set the first 3 rows as NaN

### Step 10.  Delete the rows that have NaN

### Step 11. Reset the index so it begins with 0 again

### BONUS: Create your own question and answer it.